version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: "src/Dockerfile"
        env_file: .env
        restart: always

        ports:
            - "8000:8000"
        container_name: collect_images_tiff